apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: block-a-to-b
spec:
  podSelector:
    matchLabels:
      app: service-a
  policyTypes:
    - Egress
  egress:
    # Allow to everything EXCEPT service-b
    - to:
        - namespaceSelector: {}
          podSelector:
            matchExpressions:
              - key: app
                operator: NotIn
                values:
                  - service-b
