apiVersion: v1
kind: Secret
metadata:
  name: coinstat-key
type: Opaque
stringData:
  apiKey: "${COINSTAT_KEY}"

---
apiVersion: v1
kind: Secret
metadata:
  name: coinstat-url
type: Opaque
stringData:
  apiUrl: "${COINSTAT_URL}"

---
apiVersion: v1
kind: Secret
metadata:
  name: acr-creds
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ${ACR_DOCKER_CONFIG}
