apiVersion: v1
kind: Secret
metadata:
  name: coinstat-key
type: Opaque
stringData:
  apiKey: "${COINSTAT_KEY}"

---
apiVersion: v1
kind: Secret
metadata:
  name: coinstat-url
type: Opaque
stringData:
  apiUrl: "${COINSTAT_URL}"
