name: Build & Deploy to AKS

on:
  push:
    branches:
      - main

  workflow_dispatch:

env:
  REGISTRY: ${{ secrets.ACR_URL }}
  AKS_RESOURCE_GROUP: ${{ secrets.AKS_RG }}
  AKS_CLUSTER_NAME: ${{ secrets.AKS_NAME }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout Repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Azure Login
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # ACR Login
      - name: ACR Login
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      # Build & Push service A
      - name: Build & Push service-a
        run: |
          docker build -t $REGISTRY/service-a:latest ./services/service-a
          docker push $REGISTRY/service-a:latest

      # Build & Push service B
      - name: Build & Push service-b
        run: |
          docker build -t $REGISTRY/service-b:latest ./services/service-b
          docker push $REGISTRY/service-b:latest

      # AKS - Set kubectl context
      - name: Set AKS context
        run: |
          az aks get-credentials \
            --resource-group $AKS_RESOURCE_GROUP \
            --name $AKS_CLUSTER_NAME \
            --overwrite-existing

      # Create ACR Pull Secret inside AKS
      - name: Create ACR Pull Secret
        run: |
          TOKEN=$(az acr login --name ${{ secrets.ACR_NAME }} --expose-token --query accessToken -o tsv)
          DOCKER_CONFIG_JSON=$(echo "{}" | docker login ${{ secrets.ACR_URL }} -u 00000000-0000-0000-0000-000000000000 --password $TOKEN --config ~/.docker --password-stdin >/dev/null 2>&1 && cat ~/.docker/config.json | base64 -w 0)
          sed "s|ACR_DOCKER_CONFIG_REPLACE_ME|$DOCKER_CONFIG_JSON|g" k8s/acr-secret.yaml | kubectl apply -f -

      # Apply App Secrets
      - name: Apply App Secrets
        run: |
          kubectl apply -f k8s/secrets.yaml

      # Deploy K8s Resources
      - name: Deploy Services & Deployments
        run: |
          kubectl apply -f k8s/service-a-deployment.yaml
          kubectl apply -f k8s/service-b-deployment.yaml
          kubectl apply -f k8s/service-a-service.yaml
          kubectl apply -f k8s/service-b-service.yaml
          kubectl apply -f k8s/networkpolicy.yaml
          kubectl apply -f k8s/ingress.yaml
